# Generated by Django 3.1.4 on 2021-01-17 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idCliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidoPaterno', models.CharField(max_length=50)),
                ('apellidoMaterno', models.CharField(max_length=50, null=True)),
                ('razonSocial', models.CharField(max_length=100)),
                ('calle', models.CharField(max_length=100)),
                ('numero', models.SmallIntegerField()),
                ('cp', models.SmallIntegerField(null=True)),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('numVenta', models.AutoField(primary_key=True, serialize=False)),
                ('fechaVenta', models.DateField()),
                ('totalPago', models.DecimalField(decimal_places=2, max_digits=5)),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoBarras', models.BigIntegerField()),
                ('marca', models.CharField(max_length=30)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=100)),
                ('stock', models.SmallIntegerField(null=True)),
                ('precioProvedor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('regalo', models.BooleanField(null=True)),
                ('papeleria', models.BooleanField(null=True)),
                ('impresión', models.BooleanField(null=True)),
                ('recarga', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('idProveedor', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('razonSocial', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidoPaterno', models.CharField(max_length=50)),
                ('apellidoMaterno', models.CharField(max_length=50, null=True)),
                ('calle', models.CharField(max_length=50)),
                ('numero', models.SmallIntegerField(null=True)),
                ('cp', models.SmallIntegerField(null=True)),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vende',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadArticulo', models.SmallIntegerField()),
                ('totalParcial', models.DecimalField(decimal_places=2, max_digits=5)),
                ('codigoBarras', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.producto')),
                ('numVenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Telefono_Provedor',
            fields=[
                ('telefono', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('idProveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoBarras', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.producto')),
                ('idProveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.cliente')),
            ],
        ),
    ]
