# Generated by Django 3.1.4 on 2021-01-17 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_auto_20210116_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cp',
            field=models.IntegerField(null=True),
        ),
    ]
