# Generated by Django 3.1.4 on 2021-01-17 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_auto_20210116_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='apellidoMaterno',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
