# Generated by Django 3.1.4 on 2021-01-17 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_auto_20210116_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telefono_provedor',
            name='telefono',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
