SELECT PR.RAZON_SOCIAL, PR.NOMBRE, PR.APELLIDO_PATERNO, TP.TELEFONO
FROM PROVEEDOR AS PR
INNER JOIN TELEFONO_PROVEEDOR AS TP
ON PR.PROVEEDOR_ID = TP.PROVEEDOR_ID;

SELECT CL.NOMBRE, CL.APELLIDO_PATERNO, EC.EMAIL
FROM CLIENTE AS CL
INNER JOIN EMAIL_CLIENTE AS EC
ON CL.CLIENTE_ID = EC.CLIENTE_ID

SELECT PR.CODIGO_BARRAS, PRO.RAZON_SOCIAL, PR.DESCRIPCION
FROM PRODUCTO AS PR
INNER JOIN PROVEEDOR AS PRO
ON PR.PROVEEDOR_ID = PRO.PROVEEDOR_ID
ORDER BY CODIGO_BARRAS;